import * as mongoose from 'mongoose';

export const AdvertisementSchema = new mongoose.Schema({
    accountId: { 
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Account',
    },
    createdUserId: { 
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
    },
    updatedUserId: { 
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
    },
    approvingUserId: { 
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
    },
    code: Number,
    description: String,
    status: String,
    transactionType: String,
    type: String,
    constructionType: String,
    allContentsIncluded: Boolean,
    isResidentialComplex: Boolean,
    isPenthouse: Boolean,
    bedsCount: Number,
    bathsCount: Number,
    parkingCount: Number,
    floorsCount: Number,
    constructionYear: Number,
    socioEconomicLevel: Number,
    isHoaIncluded: Boolean,
    amenities: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Amenity' }],
    communityAmenities: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Amenity' }],
    hoaFee: Number,
    lotArea: Number,
    floorArea: Number,
    price: Number,
    pricePerFloorArea: Number,
    pricePerLotArea: Number,
    propertyTax: Number,
    address: Object,
    photos: Array,
    tourUrl: String,
    videoUrl: String,
    isActive: Boolean,
    isPaid: Boolean,
    publishedAt: Date,
    isVacant: Boolean,
    vacancyDate: Date,
}, { timestamps: true, collection: 'advertisements' });